### ISSUE TITLE
Choose a "PERMISSIVE" license

### ISSUE THREAD

**Issue by AlexChesser** [AlexChesser/lgtm-shipit#17]
do it!

**Comment by chillfox** [comment]
If you intend on making money off this then consider how the licensing you chose will impact monetization options before picking a license and what you opensource. It's all about tradeoffs and, a little thinking and planning now can prevent headaches down the line.

**Comment by AlexChesser** [comment]
Thanks ChillFox! A great point.  I've been wondering if there are any repos where some folders are tagged in the ultra permissive MIT format while others are "free for usage by entities making less than ~$250k, education and not-for profit" but must be licensed at higher rates (a lot like we see on something like visual studio community edition or Unity). 

The main differentiator I want to split out is a set of automation tools that I think professional users would be willing to pay for. 

Maybe I just go MIT for this and keep the tools in a separate repo. I'll continue to "mull"

**Comment by AlexChesser** [comment]
After a couple of days of mulling it over: MIT is it.  

I'm too early in the process to have anything to feel protective of. I may as well just be as open as possible.  It seems to have worked out OK for Linus Torvalds and Ton Roosendaal.  If they can do it then maybe I can too.

If anything *significant* changes [it looks like you can change a license](https://opensource.stackexchange.com/questions/33/how-can-a-project-be-relicensed) pretty much at will.

You can't revoke a license on something that has been pushed ... which is totally fair. 

- [x] add MIT / dotnet foundation type license - permissive down to closed source commercial redistributions without attribution.

**Comment by AlexChesser** [comment]
[License added](https://github.com/AlexChesser/lgtm-shipit/blob/main/LICENSE)

It will have to change to something *likely* something like the Unity or Visual Studio Community Edition licenses where they're fully  usable in a lot of conditions *except* by businesses making more than $250k/year in order to be able to charge a nominal fee to pay developers and make the project sustainable.
