### ISSUE TITLE
Add to Apple podcasts

### ISSUE THREAD

**Issue by chillfox** [AlexChesser/lgtm-shipit#18]
No idea what the process is for this, but it is a large platform and other smaller podcast apps get their data from Apple so it would likely be beneficial to be listed there.

**Comment by AlexChesser** [comment]
Thanks! 

Some notes for when the time comes.

Documentation https://help.anchor.fm/hc/en-us/articles/360030793032-Self-submitting-your-podcast-for-distribution

- [x] validate anchor.fm has the capability to auto-submit to apple podcasts
- [ ] submit apple podcast (check if list item above works)
- [x] update anchor.fm configuration (check if item 1 works)

**Comment by AlexChesser** [comment]
@chillfox would you be ok with me thanking you during the intro to the first interview?
if yes, would you prefer “chillfox” or “Mia”? Do you have any media I can shout out for you?

**Comment by AlexChesser** [comment]
Just got word from Anchor that they've re-submitted me to Apple podcasts.  Expect up to a 2 week delay in launching on the platform, but we should get there soon.
